"""
Generate synthetic 512×512 AFM-like TIFF files with known surface statistics
for testing the PSD computation and roughness metrics.

Each file is a minimal single-page grayscale float32 TIFF that Park Systems
parseParkTiff() can read (it wraps a custom IFD structure, so we use a simple
TIFF writer that mimics the Park format the app expects).

Since parseParkTiff is proprietary, we instead write standard scientific TIFFs
that can be opened separately for validation. The primary use-case here is
numerical validation — run the PSD on these and compare to analytical results.

Usage:
    uv run tools/gen_test_tiffs.py
    # or
    python tools/gen_test_tiffs.py

Outputs: tools/test_data/*.npy  (raw float32 arrays) + analytical PSD summaries
"""

import numpy as np
from pathlib import Path

OUT = Path(__file__).parent / "test_data"
OUT.mkdir(exist_ok=True)

N = 512
L = 5.0  # scan size in µm
dx = L / N  # µm per pixel

rng = np.random.default_rng(42)


def save(name, z, desc, rms_expected=None, psd_peak_freq=None):
    arr = z.astype(np.float32)
    np.save(OUT / f"{name}.npy", arr)
    print(f"\n{'='*60}")
    print(f"  {name}: {desc}")
    print(f"  Shape: {arr.shape}, dtype: {arr.dtype}")
    print(f"  RMS:   {np.sqrt(np.mean((arr - arr.mean())**2)):.4f} nm")
    print(f"  PtP:   {arr.max() - arr.min():.4f} nm")
    if rms_expected is not None:
        print(f"  RMS expected: {rms_expected:.4f} nm")
    if psd_peak_freq is not None:
        print(f"  PSD peak freq expected: {psd_peak_freq:.3f} 1/µm")


# ── 1. White noise ────────────────────────────────────────────────────────────
# Flat PSD (all frequencies equal power).
# For Gaussian white noise with std σ, theoretical PSD ≈ σ² * dx² (constant).
sigma_wn = 1.0  # nm
z_wn = rng.normal(0, sigma_wn, (N, N)).astype(np.float32)
save("01_white_noise", z_wn,
     f"White noise σ={sigma_wn} nm. Flat PSD. RMS≈{sigma_wn} nm.",
     rms_expected=sigma_wn)

# ── 2. Checkerboard ───────────────────────────────────────────────────────────
# Square wave with period p pixels = Λ µm.
# Fundamental frequency f0 = 1/Λ 1/µm. PSD peaks at f0, 3f0, 5f0, ...
p_px = 32  # checkerboard period in pixels
Lam = p_px * dx  # µm
f0 = 1.0 / Lam  # 1/µm
xs = np.arange(N)
z_cb = np.sign(np.sin(2*np.pi * xs[None,:] / p_px) * np.sin(2*np.pi * xs[:,None] / p_px)).astype(np.float32)
# Amplitude 1 nm
save("02_checkerboard", z_cb,
     f"Checkerboard period={Lam:.3f} µm → f0={f0:.2f} 1/µm. RMS=1 nm (square wave).",
     rms_expected=1.0, psd_peak_freq=f0)

# ── 3. 1D sinusoidal grating ──────────────────────────────────────────────────
# Sine wave along x-axis. PSD spike at f_grating in 1D slice; ring in 2D.
f_grating = 2.0  # 1/µm
amp = 0.5  # nm
xs_um = np.arange(N) * dx
z_grating = (amp * np.sin(2*np.pi * f_grating * xs_um)).astype(np.float32)
z_grating = np.tile(z_grating, (N, 1))  # broadcast along y
save("03_1d_grating", z_grating,
     f"1D sinusoidal grating f={f_grating} 1/µm, A={amp} nm. RMS=A/√2={amp/np.sqrt(2):.4f} nm.",
     rms_expected=amp/np.sqrt(2), psd_peak_freq=f_grating)

# ── 4. Isotropic pink noise (1/f) ─────────────────────────────────────────────
# PSD ∝ 1/f². Common in real AFM surfaces.
# Generated by FFT: random phase, amplitude ∝ 1/f.
kx = np.fft.fftfreq(N, d=dx)  # 1/µm
ky = np.fft.fftfreq(N, d=dx)
KX, KY = np.meshgrid(kx, ky)
K = np.sqrt(KX**2 + KY**2)
K[0, 0] = 1  # avoid division by zero
amplitude = 1.0 / K  # amplitude ∝ 1/f
amplitude[0, 0] = 0  # zero DC
phase = rng.uniform(0, 2*np.pi, (N, N))
Zk = amplitude * np.exp(1j * phase)
# Enforce conjugate symmetry for real output
z_pink = np.real(np.fft.ifft2(Zk)).astype(np.float32)
z_pink -= z_pink.mean()
z_pink /= z_pink.std()  # normalize to unit std
save("04_pink_noise_1f", z_pink,
     "Pink noise (PSD ∝ 1/f²). Normalized to σ=1 nm. Typical fractal surface.",
     rms_expected=1.0)

# ── 5. Isotropic power-law roughness (1/f^4) ─────────────────────────────────
# Steeper rolloff — very smooth surfaces, common for polished substrates.
amplitude2 = 1.0 / K**2
amplitude2[0, 0] = 0
phase2 = rng.uniform(0, 2*np.pi, (N, N))
Zk2 = amplitude2 * np.exp(1j * phase2)
z_smooth = np.real(np.fft.ifft2(Zk2)).astype(np.float32)
z_smooth -= z_smooth.mean()
z_smooth /= z_smooth.std()
save("05_smooth_1f4", z_smooth,
     "Smooth power-law roughness (PSD ∝ 1/f⁴). Normalized to σ=1 nm.",
     rms_expected=1.0)

# ── 6. Tilt + white noise (tests polynomial leveling) ─────────────────────────
tilt_slope = 0.1  # nm/px
z_tilt = (tilt_slope * np.arange(N)).astype(np.float32)
z_tilt = np.tile(z_tilt, (N, 1)) + rng.normal(0, 0.2, (N, N)).astype(np.float32)
save("06_tilt_plus_noise", z_tilt,
     "Linear tilt (0.1 nm/px) + white noise σ=0.2 nm. After poly leveling, RMS→0.2 nm.")

print("\n" + "="*60)
print(f"Saved {6} test arrays to {OUT}/")
print()
print("Validation guide:")
print("  01: PSD should be flat (constant across all frequencies)")
print(f"  02: PSD should spike at f={f0:.2f} 1/µm and odd harmonics")
print(f"  03: PSD should spike at f={f_grating:.2f} 1/µm")
print("  04: log-log PSD slope ≈ -2 (pink noise)")
print("  05: log-log PSD slope ≈ -4 (smooth)")
print("  06: After poly leveling order=1: RMS ≈ 0.2 nm")
